<template>
  <div class="referral-modal" role="dialog" aria-modal="true" aria-label="수당 상세 및 지급">
    <button class="backdrop" aria-label="닫기" @click="emit('close')"></button>
    <div class="panel"><header><div><small>REFERRAL DETAILS</small><h2>{{ user?.fullName || '-' }} 회원 수당</h2><p>{{ user?.memberId || '-' }}</p></div><button aria-label="닫기" @click="emit('close')"><i class="fa-solid fa-xmark"></i></button></header>
      <div class="body"><section class="history"><div class="section-title"><div><h3>발생 내역</h3><span>총 {{ records.length }}건</span></div></div><div v-if="loading" class="modal-state">내역을 불러오는 중입니다.</div><div v-else-if="error" class="modal-state error">{{ error }}</div><div v-else-if="!records.length" class="modal-state">발생한 수당 내역이 없습니다.</div><div v-else class="history-scroll"><table><thead><tr><th>#</th><th>추천 회원</th><th>수당액</th><th>비율</th><th>첫 구매</th><th>발생일</th></tr></thead><tbody><tr v-for="(record,index) in records" :key="record._id||index"><td>{{ index+1 }}</td><td>{{ record.referredUserId?.fullName||'회원 정보 없음' }}<small>{{ record.referredUserId?.memberId||'-' }}</small></td><td><strong>{{ formatPrice(record.amount) }}</strong></td><td>{{ Number(record.percentage||0) }}%</td><td>{{ record.firstPurchase?'해당':'-' }}</td><td>{{ formatDate(record.date) }}</td></tr></tbody></table></div></section>
        <aside class="payment"><h3>수당 지급</h3><div class="unpaid-box"><span>지급 가능 금액</span><strong>{{ formatPrice(user?.unpaidReferralEarnings) }}</strong></div><dl><div><dt>예금주</dt><dd>{{ user?.fullName||'-' }}</dd></div><div><dt>은행</dt><dd>{{ user?.bankName||'-' }}</dd></div><div><dt>계좌번호</dt><dd>{{ user?.accountNumber||'-' }}</dd></div><div><dt>주민번호</dt><dd>{{ maskSsn(user?.socialSecurityNumber) }}</dd></div></dl><label><span>지급 금액</span><div><input v-model.number="payAmount" type="number" min="1" :max="user?.unpaidReferralEarnings||0" placeholder="지급 금액"><em>원</em></div></label><button class="admin-btn primary pay-button" :disabled="paying||!canPay" @click="handlePayReferral">{{ paying?'지급 처리 중':'수당 지급 처리' }}</button><p class="warning"><i class="fa-solid fa-triangle-exclamation"></i> 지급 정보를 확인한 후 처리하세요. 완료된 지급은 화면에서 취소할 수 없습니다.</p></aside>
      </div><footer><button class="admin-btn ghost" @click="emit('close')">닫기</button></footer>
    </div>
  </div>
</template>
<script setup>
import { computed,onMounted,ref } from "vue";import AdminService from "@/api/AdminService";
const props=defineProps({user:{type:Object,required:true},token:{type:String,required:true}}),emit=defineEmits(["close","updated"]);const records=ref([]),payAmount=ref(null),loading=ref(false),paying=ref(false),error=ref("");const canPay=computed(()=>Number(payAmount.value)>0&&Number(payAmount.value)<=Number(props.user?.unpaidReferralEarnings||0));const formatPrice=value=>`${Number(value||0).toLocaleString("ko-KR")}원`;const formatDate=value=>{if(!value)return "-";const date=new Date(value);return Number.isNaN(date.getTime())?"-":date.toLocaleDateString("ko-KR")};const maskSsn=value=>!value||value.length<7?"-":`${value.slice(0,7)}******`;
async function loadDetails(){loading.value=true;error.value="";try{const{data}=await AdminService.getReferralDetails(props.token,props.user._id);records.value=Array.isArray(data)?data:[]}catch(err){console.error("수당 상세 조회 실패:",err);error.value="상세 내역을 불러오지 못했습니다."}finally{loading.value=false}}
async function handlePayReferral(){if(!canPay.value)return alert("미지급 수당 범위 안에서 지급 금액을 입력해 주세요.");if(!props.user.accountNumber||!props.user.bankName)return alert("회원의 지급 계좌 정보가 등록되어 있지 않습니다.");if(!confirm(`${props.user.fullName} 회원에게 ${formatPrice(payAmount.value)}을 지급 처리하시겠습니까?`))return;paying.value=true;try{await AdminService.payReferral({userId:props.user._id,amount:Number(payAmount.value)},props.token);alert("수당 지급이 완료되었습니다.");emit("updated")}catch(err){console.error("수당 지급 실패:",err);alert(err.response?.data?.message||"수당 지급 처리에 실패했습니다.")}finally{paying.value=false}}
onMounted(loadDetails);
</script>
<style scoped>
.referral-modal{position:fixed;inset:0;z-index:2000;display:grid;place-items:center;padding:22px}.backdrop{position:absolute;inset:0;width:100%;height:100%;border:0;background:rgba(30,23,27,.58);backdrop-filter:blur(3px)}.panel{position:relative;width:min(1050px,100%);max-height:calc(100vh - 44px);display:flex;flex-direction:column;background:#fff;box-shadow:0 24px 80px rgba(20,14,17,.28)}header{display:flex;justify-content:space-between;padding:22px 24px 18px;border-bottom:1px solid #e8e0dd}header small{color:#aa7c87;font-size:.58rem;font-weight:800;letter-spacing:.18em}header h2{margin:4px 0;font-family:Georgia,"Noto Serif KR",serif;font-size:1.4rem;font-weight:400}header p{margin:0;color:#94898d;font-size:.65rem}header>button{width:38px;height:38px;border:1px solid #e2dad7;background:#fff;cursor:pointer}.body{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(270px,.7fr);gap:18px;padding:20px 24px;overflow:auto}.body section,.body aside{border:1px solid #e7dfdc}.history{min-width:0}.section-title{padding:15px;border-bottom:1px solid #e7dfdc}.section-title h3,.payment h3{margin:0;font-size:.82rem}.section-title span{color:#968b8f;font-size:.61rem}.history-scroll{overflow:auto}.history table{width:100%;min-width:620px;border-collapse:collapse}.history th,.history td{padding:11px;border-bottom:1px solid #ebe4e1;font-size:.64rem;text-align:left}.history th{color:#766b70;background:#f5f2f0}.history td small{display:block;margin-top:3px;color:#9b9194}.modal-state{min-height:190px;display:grid;place-items:center;color:#978c90;font-size:.68rem}.modal-state.error{color:#a05250}.payment{align-self:start;padding:17px}.unpaid-box{display:grid;gap:4px;margin:14px 0;padding:15px;color:#fff;background:#684c59}.unpaid-box span{font-size:.63rem}.unpaid-box strong{font-family:Georgia,serif;font-size:1.35rem;font-weight:400}.payment dl{display:grid;gap:0;margin:0 0 15px}.payment dl div{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid #eee8e5;font-size:.65rem}.payment dt{color:#94898d}.payment dd{margin:0;text-align:right}.payment label{display:grid;gap:7px}.payment label>span{font-size:.65rem;font-weight:700}.payment label>div{position:relative}.payment input{width:100%;height:42px;padding:0 34px 0 10px;border:1px solid #dcd3d0;box-sizing:border-box;outline:none}.payment label em{position:absolute;right:11px;top:50%;transform:translateY(-50%);font-size:.65rem;font-style:normal}.pay-button{width:100%;margin-top:9px}.warning{margin:12px 0 0;color:#9b6961;font-size:.59rem;line-height:1.6}footer{display:flex;justify-content:flex-end;padding:14px 24px;border-top:1px solid #e8e0dd}@media(max-width:800px){.body{grid-template-columns:1fr}.payment{width:auto}}@media(max-width:520px){.referral-modal{padding:0}.panel{max-height:100vh}.body,header{padding-inline:14px}}
</style>
