<template>
    <footer class="footer"><div class="footer-main page-shell"><div class="footer-brand"><img src="/img/logo2.png" alt="카리나벨" /><p>자연의 생명력을 담은<br />소중하고 사랑스러운 향기</p><div class="socials"><a v-for="icon in socialIcons" :key="icon.label" :href="icon.link" target="_blank" rel="noopener" :aria-label="icon.label"><i :class="icon.icon"></i></a></div></div><div class="footer-nav"><div><strong>SHOP</strong><RouterLink to="/products/onlymember">에센셜 오일</RouterLink><RouterLink to="/products/kits">키트 상품</RouterLink></div><div><strong>ABOUT</strong><RouterLink to="/about/greeting">인사말</RouterLink><RouterLink to="/about/story">브랜드 스토리</RouterLink><RouterLink to="/about/navigate">찾아오시는 길</RouterLink></div><div><strong>SUPPORT</strong><RouterLink to="/notices">공지사항</RouterLink><RouterLink to="/qna">Q&amp;A</RouterLink></div></div><div class="contact"><p class="eyebrow">CUSTOMER CENTER</p><a href="tel:042-822-2581">042. 822. 2581</a><span>평일 09:00 — 18:00<br />주말 및 공휴일 휴무</span></div></div><div class="footer-bottom page-shell"><p>카리나벨 · 대표 신은영 · 사업자등록번호 443-19-01421 · 통신판매업신고 2022-대전유성-0937<br />대전광역시 은구비남로7번길 73, 3층 301호 · karinabel@naver.com</p><div><a href="/file/카리나벨 개인정보취급방침.pdf" target="_blank">개인정보처리방침</a><a href="/file/카리나벨 이용약관.pdf" target="_blank">이용약관</a></div><small>© {{ year }} KARINABEL</small></div></footer>
</template>
<script setup>
const year=new Date().getFullYear();
const socialIcons=[{label:"인스타그램",link:"https://www.instagram.com/",icon:"fa-brands fa-instagram"},{label:"유튜브",link:"https://www.youtube.com/",icon:"fa-brands fa-youtube"},{label:"네이버 블로그",link:"https://blog.naver.com/",icon:"fa-solid fa-n"}];
</script>
<style scoped>
.footer{padding-top:75px;color:#ddd4d8;background:#292326}.footer-main{display:grid;grid-template-columns:1.1fr 1.8fr 1fr;gap:70px;padding-bottom:65px}.footer-brand img{width:150px;height:60px;object-fit:contain;filter:grayscale(1) brightness(4)}.footer-brand p{margin-top:18px;color:#a99da2;font-size:.85rem;line-height:1.8}.socials{display:flex;gap:10px;margin-top:25px}.socials a{width:34px;height:34px;display:grid;place-items:center;border:1px solid #554a4f;border-radius:50%;font-size:.8rem}.footer-nav{display:grid;grid-template-columns:repeat(3,1fr);gap:30px}.footer-nav strong{display:block;margin-bottom:19px;color:#fff;font-size:.7rem;letter-spacing:.14em}.footer-nav a{display:block;margin:9px 0;color:#a99da2;font-size:.8rem}.contact .eyebrow{color:#bda2af}.contact>a{display:block;margin:10px 0 12px;color:#fff;font-family:Georgia,serif;font-size:1.75rem}.contact span{color:#a99da2;font-size:.78rem}.footer-bottom{position:relative;display:flex;align-items:flex-end;justify-content:space-between;gap:30px;padding-block:27px;border-top:1px solid #433a3e;color:#82767b;font-size:.68rem}.footer-bottom div{display:flex;gap:18px;white-space:nowrap}.footer-bottom div a:first-child{color:#c7bac0;font-weight:700}.footer-bottom small{white-space:nowrap}
@media(max-width:900px){.footer-main{grid-template-columns:1fr 1fr}.footer-nav{grid-row:2;grid-column:1/-1}.footer-bottom{flex-wrap:wrap}.footer-bottom p{width:100%}}@media(max-width:600px){.footer{padding-top:55px}.footer-main{grid-template-columns:1fr;gap:40px}.footer-nav{grid-row:auto;grid-column:auto;gap:14px}.contact{padding-top:10px}.footer-bottom{align-items:flex-start;flex-direction:column}.footer-bottom div{order:-1}}
</style>
