<template>
  <div class="admin-layout">
    <AdminSidebar :open="menuOpen" @navigate="menuOpen=false" />
    <div v-if="menuOpen" class="admin-overlay" @click="menuOpen=false"></div>
    <div class="admin-workspace">
      <header class="admin-topbar">
        <div><button type="button" class="menu-toggle" aria-label="관리자 메뉴 열기" @click="menuOpen=true"><i class="fa-solid fa-bars"></i></button><div><p>{{section.eyebrow}}</p><strong>{{section.title}}</strong></div></div>
        <div class="admin-account"><span><i class="fa-regular fa-user"></i></span><p><strong>{{adminName}}</strong><small>Administrator</small></p><button type="button" @click="logout"><i class="fa-solid fa-arrow-right-from-bracket"></i><span>로그아웃</span></button></div>
      </header>
      <main class="admin-main"><router-view /></main>
    </div>
  </div>
</template>
<script setup>
import{computed,ref,watch}from"vue";import{useRoute,useRouter}from"vue-router";import{useStore}from"vuex";import AdminSidebar from"@/components/admin/AdminSidebar.vue";
const route=useRoute(),router=useRouter(),store=useStore(),menuOpen=ref(false);const adminName=computed(()=>store.state.user?.fullName||"관리자");
const labels={AdminDashboardView:["OVERVIEW","대시보드"],AdminMemberManageView:["MEMBERS","회원 관리"],AdminWithdrawnMemberManageView:["MEMBERS","탈퇴회원 관리"],AdminReferralView:["MEMBERS","수당 관리"],AdminOrderManageView:["ORDERS","주문 관리"],DeliveryStatusView:["ORDERS","배송 현황"],AdminShippingView:["ORDERS","배송 관리"],AdminOrderCancleView:["ORDERS","주문 취소"],AdminManualOrderView:["ORDERS","수기 입력"],ProductManageView:["CATALOG","상품 관리"],KitManageView:["CATALOG","키트 관리"],NoticeManagerView:["CONTENT","공지사항"],AnswerManagerView:["CONTENT","Q&A 답변"]};
const section=computed(()=>{const value=labels[route.name]||["ADMIN","관리자 페이지"];return{eyebrow:value[0],title:value[1]}});watch(()=>route.fullPath,()=>menuOpen.value=false);const logout=()=>{store.dispatch("logout");router.replace("/admin/login")};
</script>
<style>
.admin-layout{min-height:100vh;color:#302a2d;background:#f5f2f0;font-family:"Pretendard","Noto Sans KR",sans-serif}.admin-workspace{min-height:100vh;margin-left:260px}.admin-topbar{position:sticky;top:0;z-index:900;height:82px;display:flex;align-items:center;justify-content:space-between;padding:0 30px;border-bottom:1px solid #e6dfdc;background:rgba(255,255,255,.94);backdrop-filter:blur(15px)}.admin-topbar>div{display:flex;align-items:center;gap:13px}.admin-topbar p{color:#aa7c87;font-size:.52rem;font-weight:800;letter-spacing:.15em}.admin-topbar strong{display:block;margin-top:1px;font-size:.9rem}.menu-toggle{display:none;width:40px;height:40px;border:1px solid #e2dad7;background:#fff;color:#554a4f}.admin-account>span{width:36px;height:36px;display:grid;place-items:center;border-radius:50%;color:#765663;background:#f1e7e9}.admin-account p strong{font-size:.72rem}.admin-account p small{display:block;color:#a0969a;font-size:.52rem}.admin-account>button{height:36px;padding:0 12px;border:1px solid #ded5d8;color:#756a6f;background:#fff;font-size:.63rem}.admin-account>button i{margin-right:6px}.admin-main{padding:30px;overflow:hidden}.admin-main>div{max-width:1500px;margin-inline:auto}.admin-overlay{display:none}
.admin-main button{border-radius:2px}.admin-main input,.admin-main select,.admin-main textarea{border-radius:2px!important}.admin-main table{border-collapse:collapse}.admin-main thead{color:#62585d;background:#f0ecea!important}.admin-main th,.admin-main td{border-color:#e9e2df!important}.admin-main button:not([class*="page"]):not([class*="tab"]):not([class*="filter"]){transition:.2s}
@media(max-width:900px){.admin-workspace{margin-left:0}.admin-topbar{height:70px;padding:0 16px}.menu-toggle{display:grid;place-items:center}.admin-account p{display:none}.admin-account>button span{display:none}.admin-account>button i{margin:0}.admin-main{padding:18px 12px 50px}.admin-overlay{position:fixed;inset:0;z-index:1100;display:block;background:rgba(25,18,22,.42)}}
</style>
<style>
.admin-main .admin-count{min-width:96px;min-height:58px;display:inline-flex!important;align-items:baseline;justify-content:center;gap:6px;box-sizing:border-box}
.admin-main .admin-count strong,.admin-main .admin-count span{display:inline!important;margin:0!important;white-space:nowrap;line-height:1}
@media(max-width:640px){.admin-main .admin-count{min-width:78px;min-height:50px}}
.admin-main .editor-card{overflow:hidden!important;padding:0!important;border-color:#ded5d3!important;box-shadow:0 10px 32px rgba(56,39,47,.06)!important}.admin-main .editor-head{align-items:center!important;margin:0!important;padding:20px 22px!important;border-bottom:1px solid #e7ddda!important;background:linear-gradient(135deg,#f7edef,#fbf8f7)!important}.admin-main .editor-head h2{font-size:1.35rem!important}.admin-main .editor-card form{gap:15px!important;padding:21px 22px 23px!important}.admin-main .editor-card label>span{color:#63595d!important;font-size:.67rem!important}.admin-main .editor-card input,.admin-main .editor-card textarea{width:100%!important;padding:11px 12px!important;border:1px solid #d9d0cd!important;background:#fff!important;box-sizing:border-box!important;line-height:1.65!important}.admin-main .editor-card input:focus,.admin-main .editor-card textarea:focus{border-color:#916c79!important;box-shadow:0 0 0 3px rgba(145,108,121,.1)!important}.admin-main .editor-submit{min-height:44px!important;margin-top:2px!important}
</style>
<style>
.admin-main :is(.adminMemberList,.adminOrderList,.adminOrderStatus,.adminPageWrapper,.adminQnaList,.manualInputPage,.productManagerContainer,.adminNoticeList,.adminCancelPage){width:100%!important;max-width:1500px!important;margin:0 auto!important;padding:0!important}
.admin-main .pageTitle{margin:0 0 24px!important;color:#302a2d!important;font-family:Georgia,"Noto Serif KR",serif!important;font-size:clamp(1.6rem,2.5vw,2.2rem)!important;font-weight:400!important}
.admin-main :is(.filterBar,.filterSection){border-radius:2px!important;box-shadow:none!important}.admin-main table{width:100%;background:#fff}.admin-main button:disabled{opacity:.45;cursor:not-allowed}

/* Shared admin data screens */
.admin-data-page{display:grid;gap:18px}.admin-page-head{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;padding:4px 2px 10px}.admin-page-head p{margin:0 0 8px;color:#aa7c87;font-size:.63rem;font-weight:800;letter-spacing:.2em}.admin-page-head h1{margin:0;color:#302a2d;font-family:Georgia,"Noto Serif KR",serif;font-size:clamp(1.7rem,2.8vw,2.35rem);font-weight:400;line-height:1.15}.admin-page-head>div>span{display:block;margin-top:9px;color:#84797e;font-size:.77rem}.admin-count{min-width:82px;padding:12px 15px;border:1px solid #e3dad7;background:#fff;text-align:center}.admin-count strong{font-family:Georgia,serif;font-size:1.45rem;font-weight:400}.admin-count span{margin-left:5px;color:#92878c;font-size:.68rem}.admin-count.warning{color:#9a5c49;background:#fbf3ef}
.admin-filter-card{display:flex;align-items:flex-end;gap:12px;flex-wrap:wrap;padding:18px;border:1px solid #e5dedb;background:#fff}.admin-filter-card label{display:grid;min-width:150px;gap:7px}.admin-filter-card label>span{color:#756a6f;font-size:.67rem;font-weight:700}.admin-filter-card input,.admin-filter-card select,.admin-bulk select,.admin-inline-control select,.trx-input{height:40px;padding:0 11px;border:1px solid #ddd4d1;background:#fff;color:#40383c;font:inherit;font-size:.72rem;outline:none}.admin-filter-card input:focus,.admin-filter-card select:focus,.admin-bulk select:focus,.admin-inline-control select:focus,.trx-input:focus{border-color:#916c79;box-shadow:0 0 0 3px rgba(145,108,121,.1)}.admin-date-range{display:flex;align-items:center;gap:7px}.admin-date-range input{min-width:132px}.admin-date-range i{color:#b2a8ac;font-style:normal}.admin-filter-actions{display:flex;gap:7px;margin-left:auto}
.admin-btn{min-height:40px;padding:0 15px;border:1px solid transparent!important;border-radius:2px!important;font-family:inherit;font-size:.69rem;font-weight:700;white-space:nowrap;cursor:pointer;transition:border-color .2s,background .2s,color .2s,transform .2s}.admin-btn:hover:not(:disabled){transform:translateY(-1px)}.admin-btn i{margin-right:6px}.admin-btn.primary{color:#fff;background:#684c59}.admin-btn.primary:hover{background:#503942}.admin-btn.secondary{color:#fff;background:#373135}.admin-btn.secondary:hover{background:#211d20}.admin-btn.ghost{border-color:#dcd3d0!important;color:#62575c;background:#fff}.admin-btn.ghost:hover{border-color:#a88c96!important;background:#faf7f6}.admin-btn.danger{color:#fff;background:#a65353}.admin-btn.danger:hover{background:#884141}.admin-btn.small{min-height:34px;padding:0 11px;font-size:.65rem}
.admin-notice{display:flex;align-items:center;gap:13px;padding:13px 16px;border:1px solid #e4dcda;color:#685e62;background:#faf8f7}.admin-notice>i{color:#9b7582}.admin-notice p{display:grid;gap:2px;margin:0;font-size:.72rem}.admin-notice p span{color:#91868a;font-size:.66rem}.admin-notice.danger{border-color:#ead3ce;color:#844c43;background:#fcf4f1}.admin-notice.danger>i{color:#b45d50}
.admin-table-card{min-width:0;border:1px solid #e3dcda;background:#fff}.admin-table-toolbar{display:flex;align-items:center;justify-content:space-between;gap:15px;min-height:68px;padding:13px 17px;border-bottom:1px solid #ebe5e2}.admin-table-toolbar>div:first-child{display:grid;gap:3px}.admin-table-toolbar strong{font-size:.81rem}.admin-table-toolbar span{color:#94898d;font-size:.64rem}.toolbar-actions,.admin-bulk{display:flex;align-items:center;gap:7px}.admin-bulk select{min-width:135px}.admin-table-scroll{width:100%;overflow-x:auto}.admin-table{min-width:900px}.admin-table th{padding:12px 14px;border:0;border-bottom:1px solid #e7dfdc!important;color:#756b6f;background:#f4f1ef!important;font-size:.64rem;font-weight:700;text-align:left;white-space:nowrap}.admin-table td{padding:13px 14px;border:0;border-bottom:1px solid #eee8e5!important;color:#51484c;font-size:.7rem;vertical-align:middle}.admin-table tbody tr:last-child td{border-bottom:0!important}.admin-table tbody tr:hover{background:#fcfaf9}.admin-table td.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:.67rem}.admin-table .check{width:42px;text-align:center}.admin-table input[type=checkbox]{width:15px;height:15px;accent-color:#765663}.admin-primary-cell{display:grid;gap:3px}.admin-primary-cell strong{font-size:.72rem}.admin-primary-cell small{color:#9a9094;font-size:.61rem}.admin-address{min-width:220px;max-width:320px}.admin-product{min-width:160px}.admin-reason{min-width:180px;max-width:300px;white-space:normal}.admin-chip,.admin-status{display:inline-flex;align-items:center;min-height:25px;padding:0 9px;border-radius:999px;color:#714f5d;background:#f1e6ea;font-size:.62rem;font-weight:700;white-space:nowrap}.admin-chip.muted{color:#746b6e;background:#f1efee}.admin-status[data-status="배송완료"],.admin-status[data-status="구매확정"]{color:#39705a;background:#e7f3ed}.admin-status[data-status="취소중"],.admin-status[data-status="반품중"]{color:#9a5048;background:#f8e8e5}.admin-status[data-status="배송중"],.admin-status[data-status="상품준비중"]{color:#6c6294;background:#eeeaf8}.admin-inline-control{display:flex;gap:6px}.admin-inline-control select{min-width:105px}.trx-input{width:180px}.admin-state{min-height:240px;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:10px;color:#968b8f;text-align:center}.admin-state>i{font-size:1.3rem}.admin-state p{margin:0;font-size:.73rem}.admin-state.compact{min-height:150px}.admin-state.error{color:#9b514d}.admin-state.success{color:#52816c}
@media(max-width:1100px){.admin-filter-actions{margin-left:0}.admin-filter-card label{flex:1;min-width:190px}.admin-filter-actions{width:100%;justify-content:flex-end}}
@media(max-width:640px){.admin-data-page{gap:13px}.admin-page-head{align-items:flex-start}.admin-count{min-width:65px;padding:9px}.admin-page-head>div>span{font-size:.7rem}.admin-filter-card{padding:14px}.admin-filter-card label{width:100%;min-width:100%}.admin-date-range input{width:calc(50% - 13px);min-width:0}.admin-filter-actions{display:grid;grid-template-columns:1fr 1fr}.admin-filter-actions .admin-btn{width:100%}.admin-table-toolbar{align-items:flex-start;flex-direction:column}.toolbar-actions,.admin-bulk{width:100%}.toolbar-actions .admin-btn,.admin-bulk .admin-btn{flex:1}.admin-bulk select{flex:1;min-width:0}.admin-notice{align-items:flex-start}}
</style>
