<template>
  <section class="admin-data-page">
    <header class="admin-page-head"><div><p>REFERRALS</p><h1>추천 수당 관리</h1><span>회원별 수당 현황을 확인하고 지급 내역을 처리합니다.</span></div><div class="admin-count"><strong>{{ total.toLocaleString() }}</strong><span>명</span></div></header>
    <form class="admin-filter-card" @submit.prevent="searchUsers(1)"><label><span>회원 이름</span><input v-model.trim="searchName" placeholder="이름"></label><label><span>회원번호</span><input v-model.trim="searchMemberId" placeholder="회원번호"></label><label><span>은행명</span><input v-model.trim="searchBank" placeholder="은행명"></label><div class="admin-filter-actions"><button type="button" class="admin-btn ghost" @click="resetFilters">초기화</button><button class="admin-btn primary" :disabled="loading"><i class="fa-solid fa-magnifying-glass"></i> 검색</button></div></form>
    <div class="admin-notice"><i class="fa-solid fa-shield-halved"></i><p><strong>개인정보 보호 적용</strong><span>주민등록번호는 화면과 엑셀 파일에서 마스킹되며, 행을 선택하면 수당 상세 내역을 확인할 수 있습니다.</span></p></div>
    <div class="admin-table-card"><div class="admin-table-toolbar"><div><strong>회원별 수당 현황</strong><span>현재 페이지 미지급액 {{ formatPrice(totalUnpaid) }}</span></div><button class="admin-btn secondary" :disabled="loading||!total" @click="downloadReferralExcel"><i class="fa-solid fa-file-arrow-down"></i> 엑셀 다운로드</button></div>
      <div v-if="error" class="admin-state error"><i class="fa-solid fa-circle-exclamation"></i><p>{{ error }}</p><button class="admin-btn ghost" @click="searchUsers(currentPage)">다시 시도</button></div><div v-else class="admin-table-scroll"><table class="admin-table"><thead><tr><th>회원</th><th>총 수당</th><th>지급 수당</th><th>미지급 수당</th><th>계좌번호</th><th>은행</th><th>주민번호</th><th>상세</th></tr></thead><tbody>
        <tr v-if="loading"><td colspan="8"><div class="admin-state compact"><i class="fa-solid fa-spinner fa-spin"></i><p>수당 정보를 불러오는 중입니다.</p></div></td></tr><tr v-else-if="!referralList.length"><td colspan="8"><div class="admin-state compact"><i class="fa-regular fa-folder-open"></i><p>조건에 맞는 회원이 없습니다.</p></div></td></tr>
        <tr v-for="user in referralList" :key="user._id"><td><div class="admin-primary-cell"><strong>{{ user.fullName||'-' }}</strong><small>{{ user.memberId||'-' }}</small></div></td><td>{{ formatPrice(user.totalReferralEarnings) }}</td><td>{{ formatPrice(user.paidReferralEarnings) }}</td><td><strong class="unpaid">{{ formatPrice(user.unpaidReferralEarnings) }}</strong></td><td class="mono">{{ maskAccount(user.accountNumber) }}</td><td>{{ user.bankName||'-' }}</td><td class="mono">{{ maskSsn(user.socialSecurityNumber) }}</td><td><button class="admin-btn small ghost" @click="openModal(user)">내역·지급</button></td></tr>
      </tbody></table></div>
    </div>
    <Pagination v-if="!loading&&totalPages>1" :current-page="currentPage" :total-pages="totalPages" @page-change="searchUsers" />
    <RefferalModal v-if="showModal" :user="selectedUser" :token="token" @close="showModal=false" @updated="handleUpdated" />
  </section>
</template>
<script setup>
import { computed,onMounted,ref } from "vue";import * as XLSX from "xlsx";import AdminService from "@/api/AdminService";import RefferalModal from "@/components/admin/RefferalModal.vue";import Pagination from "@/components/common/Pagination.vue";import { getStoredToken } from "@/utils/storage";
const referralList=ref([]),showModal=ref(false),selectedUser=ref(null),searchName=ref(""),searchMemberId=ref(""),searchBank=ref(""),currentPage=ref(1),totalPages=ref(1),total=ref(0),loading=ref(false),error=ref(""),pageSize=20,token=getStoredToken();const totalUnpaid=computed(()=>referralList.value.reduce((sum,user)=>sum+Number(user.unpaidReferralEarnings||0),0));const formatPrice=value=>`${Number(value||0).toLocaleString("ko-KR")}원`;const maskSsn=value=>!value||value.length<7?"-":`${value.slice(0,7)}******`;const maskAccount=value=>{if(!value)return "-";const clean=String(value);return clean.length<8?clean:`${clean.slice(0,4)}••••${clean.slice(-4)}`};const params=(page,size=pageSize)=>({name:searchName.value,memberId:searchMemberId.value,bankName:searchBank.value,page,size});
async function searchUsers(page=1){currentPage.value=page;loading.value=true;error.value="";try{const{data}=await AdminService.getReferralEarningsList(token,params(page));referralList.value=data.users||[];total.value=data.total||0;totalPages.value=Math.max(1,Math.ceil(total.value/pageSize))}catch(err){console.error("추천 수당 목록 조회 실패:",err);referralList.value=[];total.value=0;error.value="추천 수당 정보를 불러오지 못했습니다."}finally{loading.value=false}}
function resetFilters(){searchName.value="";searchMemberId.value="";searchBank.value="";searchUsers(1)}function openModal(user){selectedUser.value=user;showModal.value=true}function handleUpdated(){showModal.value=false;searchUsers(currentPage.value)}
async function downloadReferralExcel(){try{const{data}=await AdminService.getReferralEarningsList(token,params(1,10000));const rows=(data.users||[]).map((user,index)=>({번호:index+1,이름:user.fullName,회원번호:user.memberId,총수당:Number(user.totalReferralEarnings||0),지급수당:Number(user.paidReferralEarnings||0),미지급수당:Number(user.unpaidReferralEarnings||0),계좌번호:user.accountNumber||"-",은행명:user.bankName||"-",주민번호:maskSsn(user.socialSecurityNumber)}));if(!rows.length)return alert("다운로드할 데이터가 없습니다.");const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(rows),"수당목록");XLSX.writeFile(book,`수당목록_${new Date().toISOString().slice(0,10)}.xlsx`)}catch(err){console.error("수당 엑셀 다운로드 실패:",err);alert("엑셀 파일을 만들지 못했습니다.")}}
onMounted(()=>searchUsers());
</script>
<style scoped>.unpaid{color:#a1545f}.admin-table tbody tr{cursor:default}</style>
